services:

#--------------------------------------------------------------------------
  backend:
    build:
      context: ./java
    container_name: base-backend
    volumes:
      - ./logs/jvm:/app/logs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: ${SYSTEM_TZ}
      MYBATIS_FLEX_DATASOURCE_MASTER_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_PARAMS}
      MYBATIS_FLEX_DATASOURCE_MASTER_USERNAME: ${DB_USERNAME}
      MYBATIS_FLEX_DATASOURCE_MASTER_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-tier
  frontend:
    build:
      context: ./vue
    container_name: base-frontend
    restart: always
    volumes:
      - ./logs/nginx:/var/log/nginx
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 64M
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - backend
    networks:
      - app-tier
#-------------------------------------------------------------------------
  goaccess:
    image: allinurl/goaccess:latest
    container_name: base-monitor
    network_mode: none
    profiles:
      - tools
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    volumes:
      - ./logs/nginx:/srv/logs
    entrypoint: [ "goaccess", "/srv/logs/access.log", "--log-format=COMBINED", "--no-global-config", "--output=/srv/logs/report.html" ]
#-------------------------------------------------------------------------
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: base-cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - '--port=9999'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
    expose:
      - "9999"
    networks:
      - app-tier
#-------------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: base-prometheus
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 128M
    expose:
      - 9090
    volumes:
      - ./observer/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./observer/data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    depends_on:
      - backend
    networks:
      - app-tier
#-------------------------------------------------------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: base-grafana
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      TZ: ${SYSTEM_TZ}
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./observer/data/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-tier
#-------------------------------------------------------------------------
networks:
  app-tier:
    driver: bridge