services:
  backend:
    build:
      context: ./java
    container_name: base-backend
    restart: always
    ports:
      - "8080:80"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: ${SYSTEM_TZ}
      MYBATIS_FLEX_DATASOURCE_MASTER_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_PARAMS}
      MYBATIS_FLEX_DATASOURCE_MASTER_USERNAME: ${DB_USERNAME}
      MYBATIS_FLEX_DATASOURCE_MASTER_PASSWORD: ${DB_PASSWORD}

  frontend:
    build:
      context: ./vue
    container_name: base-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend