spring.application.name=base
spring.threads.virtual.enabled=true
server.port=80
server.address=0.0.0.0
spring.mvc.servlet.load-on-startup=1

spring.mvc.problemdetails.enabled=true

spring.messages.basename=Internationalization/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
spring.messages.cache-duration=3600

server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=text/plain,text/html,text/xml,application/json,application/javascript,text/css,application/xml

spring.profiles.active=dev

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.initialization-fail-timeout=5000

spring.sql.init.schema-locations=classpath:META-INF/warming/warmup.sql

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis-flex.datasource.master.url=jdbc:mysql://localhost:3306/connector?TimeZone=Asia/Shanghai
mybatis-flex.datasource.master.username=root
mybatis-flex.datasource.master.password=root

mybatis-flex.datasource.slave.url=jdbc:mysql://localhost:3306/connector?TimeZone=Asia/Shanghai
mybatis-flex.datasource.slave.username=root
mybatis-flex.datasource.slave.password=root

server.servlet.session.cookie.name=trace
server.servlet.session.cookie.max-age=2h
server.tomcat.max-connections=65535

mybatis-flex.global-config.print-banner=false

#server.servlet.session.cookie.same-site=lax
#server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.partitioned=true

server.http2.enabled=true
#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-password=your_password
#server.ssl.key-password=your_password
#server.ssl.key-alias=springboot-cert