name: build-java

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: maven:3.9.9-eclipse-temurin-21

    steps:

      - name: clone
        env:
          GITEA_TOKEN: 3fa3dc8de6e269cd8d20d09f0bb93051b286b4e4
        run: |
          git config --global http.extraHeader "Authorization: token ${GITEA_TOKEN}"
          git clone http://47.121.125.149:3000/mizuki/basement source

      - name: build
        run: |
          cd source
          mvn clean package -DskipTests

      - name: prepare artifact
        run: |
          mkdir -p artifact
          JAR=$(find source/target -name "*.jar" | head -n 1)
          cp "$JAR" artifact/app.jar

      - name: upload package
        env:
          GITEA_TOKEN: 3fa3dc8de6e269cd8d20d09f0bb93051b286b4e4
        run: |
          VERSION=$(date +%Y%m%d-%H%M%S)

          curl -X PUT \
            --user UwU:${GITEA_TOKEN} \
            --upload-file artifact/app.jar \
            http://47.121.125.149:3000/api/packages/mizuki/generic/basement/${VERSION}/app.jar