name: build-and-push-image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: build jar
        run: |
          mvn clean package -DskipTests

      - name: set version
        run: |
          echo "VERSION=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: docker login
        run: |
          echo "3fa3dc8de6e269cd8d20d09f0bb93051b286b4e4" | docker login 47.121.125.149:3000 \
            -u mizuki \
            --password-stdin

      - name: build docker image
        run: |
          docker build -t 47.121.125.149:3000/mizuki/basement:${VERSION} .
          docker tag 47.121.125.149:3000/mizuki/basement:${VERSION} \
                     47.121.125.149:3000/mizuki/basement:latest

      - name: push image
        run: |
          docker push 47.121.125.149:3000/mizuki/basement:${VERSION}
          docker push 47.121.125.149:3000/mizuki/basement:latest