name: build-java

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: maven:3.9.9-eclipse-temurin-21

    steps:

      - name: clone
        run: |
          git clone http://47.121.125.149:3000/UwU/basement.git source

      - name: build
        run: |
          cd source
          mvn clean package -DskipTests

      - name: prepare artifact
        run: |
          mkdir -p artifact
          JAR=$(find source/target -name "*.jar" | head -n 1)
          cp "$JAR" artifact/app.jar

      - name: upload package
        env:
          GITEA_TOKEN: ce28902bb9f56a326a5abe5c967a2871d664ee7f
        run: |
          VERSION=$(date +%Y%m%d-%H%M%S)

          curl -X PUT \
            --user UwU:${GITEA_TOKEN} \
            --upload-file artifact/app.jar \
            http://47.121.125.149:3000/api/packages/UwU/generic/basement/${VERSION}/app.jar