name: build-java

on:
  workflow_dispatch:
    inputs:
      version:
        description: "release version"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.9-eclipse-temurin-21

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: show info
        run: |
          echo "version=${{ inputs.version }}"
          java -version
          mvn -version

      - name: build
        run: |
          mvn clean package -DskipTests

      - name: list artifact
        run: |
          ls -lh target/

      - name: rename jar
        run: |
          mkdir artifact
          JAR=$(find target -name "*.jar" | head -n 1)
          cp "$JAR" artifact/app.jar

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: artifact/app.jar