logging.level.org.springframework.web.servlet.PageNotFound=ERROR

management.endpoints.web.exposure.include=prometheus
management.health.defaults.enabled=false
management.metrics.tags.application=base-backend
management.prometheus.metrics.export.enabled=true

mybatis-flex.datasource.master.url=${MYBATIS_FLEX_DATASOURCE_MASTER_URL:jdbc:mysql://127.0.0.1:3306/connector?TimeZone=Asia/Shanghai}
mybatis-flex.datasource.master.username=${MYBATIS_FLEX_DATASOURCE_MASTER_USERNAME:root}
mybatis-flex.datasource.master.password=${MYBATIS_FLEX_DATASOURCE_MASTER_PASSWORD:root}

spring.sql.init.mode=always