spring.main.lazy-initialization=true

mybatis-flex.datasource.master.url=jdbc:mysql://localhost:3306/connector?TimeZone=Asia/Shanghai
mybatis-flex.datasource.master.username=root
mybatis-flex.datasource.master.password=root

spring.sql.init.mode=never